config/routes.rb
require 'sidekiq/web'

Redirectme::Application.routes.draw do
  devise_for :users
  mount Sidekiq::Web, at: '/sidekiq'

  devise_scope :user do
    root "devise/registrations#new"
  end

  resources :groups
  get '/feedback' => 'application#feedback', as: :feedback

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :rules, dependent: :delete_all
  belongs_to :user

  accepts_nested_attributes_for :rules

  before_save :generate_cache

  validates :full_url, uniqueness: true

  def generate_cache
    Rails.cache.delete cache_key if full_url.present?
    Rails.cache.write cache_key, rules_proc, raw: true
  end

  def name_or_generate count
    name || I18n.t('group_default_name', id: count)
  end

  def cache_key
    "group:#{full_url}"
  end

  def self.cache_key url
    "group:#{url}"
  end

  def service_domain?
    domain.in? $GLOBAL[:service_hosts]
  end

  def rules_proc
    acum = 0
    expression = rules.map do |rule|
      acum += rule.expression.to_f
      ["random < #{acum}", "'#{rule.url}'"].join(' && ')
    end

    "-> (random, data) {#{[ expression, "'#{rules.first.url}'" ].join(' || ')}}"
  end
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :group
  belongs_to :parent, class_name: 'Rule', foreign_key: :parent_id
  has_many :childs, class_name: 'Rule', foreign_key: :parent_id, dependent: :nullify

  def generate_cache_count
    Rails.cache.write count_cache_key, 0, raw: true, unless_exist: true
    count_cache_key
  end

  def count_cache_key
    "rule_hit_count:#{group.full_url}:#{url}"
  end

  def reset_cached_count
    Rails.cache.write count_cache_key, 0, raw: true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # has_mobile_fu
  helper_method :is_mobile_device?, :production?

  def is_mobile_device?
    false
  end

  def after_sign_in_path_for(resource)
    groups_path
  end

  def production?
    @is_production ||= ENV['RAILS_ENV'] == 'production'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_filter -> { redirect_to new_group_path }, only: :index, if: -> { current_user.groups.empty? }

  # GET /groups
  def index
    @groups = current_user.groups
  end

  # GET /groups/1
  def show
    render 'edit'
  end

  # GET /groups/new
  def new
    @group = current_user.groups.new(domain: request.host_with_port)
    render 'edit'
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  def create
    @group = current_user.groups.new(group_params)

    if @group.save
      redirect_to groups_path, flash: { success: I18n.t('group.created') }
    else
      render action: 'edit'
    end
  end

  # PATCH/PUT /groups/1
  def update
    if @group.update(group_params)
      redirect_to groups_path, flash: { success: I18n.t('group.updated') }
    else
      render action: 'edit'
    end
  end

  # DELETE /groups/1
  def destroy
    @group.destroy
    redirect_to groups_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = current_user.groups.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :full_url, rules_attributes: [:id, :url, :expression])
    end
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rule }
      else
        format.html { render action: 'new' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:master, :user_id, :url, :expression)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def footer_javascript(*args, &block)
    content_for :footer_scripts, javascript_include_tag(*args)
    content_for :footer_scripts, &block if block_given?
  end

  def flash_class type
    case type
    when :success then 'success'
    when :error then 'alert'
    when :alert then 'warning'
    else ''
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/application/feedback.html.erb
<h1><%= t('.title') %></h1>
<p><%= t('.description')%></p>
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'redirectme'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>

app/views/examples/page_with_green_button.html.haml
%h1= t('.title')
%a.button.success= t('.green_button')

app/views/examples/page_with_red__button.html.haml
%h1= t('.title')
%a.button.alert= t('.red_button')

app/views/groups/_form.html.haml
- rules = @group.rules.all
- rules = [ Rule.new(expression: 100) ] if rules.empty?
%span#help_button.label.round.secondary{role: 'joyride-starter'} ?
#group
  %h2#group-title
    =  @group.persisted? ? t('.group') : t('.new_group')
  = form_for @group do |f|
    .row
      .columns
        .row.collapse
          = f.text_field :name, id: :group_name, placeholder: t('.name'), role: 'group-name', value: @group.name_or_generate(Group.count + 1)
        #url.row.collapse
          .small-2.medium-1.large-1.columns
            %label#group-url
              URL:
          .small-10.medium-11.large-11.columns
            = f.text_field :full_url, id: :full_url, role: 'group-url', value: @group.full_url
          / .small-11.medium-2.large-2.columns
          /   = f.text_field :subdomain, id: :subdomain, placeholder: t('.subdomain'), value: @group.subdomain
          / .small-1.medium-1.large-1.columns
          /   %span.postfix .
          / .medium-5.large-5.columns
          /   = f.text_field :domain, id: :domain, placeholder: t('.domain'), value: @group.domain
          / .small-2.medium-1.large-1.columns
          /   %span.prefix.fight= $GLOBAL[:category_prefix]
          / .small-10.medium-2.large-2.columns
          /   = f.text_field :category, id: :category, placeholder: t('.categotry'), value: @group.category
    #rules
      .row
        %h3#rules-title.left
          = t('.rules')
      - rules.each do |rule|
        = hidden_field_tag 'group[rules_attributes][][id]', rule.id
        .row.rule{role: :rule}
          .large-5.columns
            = url_field_tag 'group[rules_attributes][][url]', rule.url, placeholder: t('.target_url'), role: 'rule-url'
          .medium-8.large-5.columns.slider-wrapper
            %div.rule_perc_slider{role: :slider}
          .medium-4.large-2.columns
            .row.collapse
              .small-2.large-4.columns
                %a.button.prefix.locker{role: :locker}
                  %i.fi-unlock
              .small-6.large-8.columns
                = text_field_tag 'group[rules_attributes][][expression]', rule.expression, role: :value
              / .small-2.large-3.columns
              /   %a.postfix.button{role: :decrese}
              /     %i.fi-minus
              / .small-2.large-3.columns
              /   %a.postfix.button{role: :increse}
              /     %i.fi-plus
    .row
      .medium-6.large-4.columns
        %a#add-rule.button.small.left{role: 'add-rule'}
          = t('.add_rule')
          %i.fi-plus
      .medium-6.large-4.columns
        %a#stabilize.button.success.small.right{role: :stabilize}
          = t('.stabilize')
          &nbsp;
          %i.fi-arrows-in
          &nbsp;
          %span.probability-sum
      .medium-6.large-4.columns
        = f.submit t('.save'), class: 'button small', role: :save, id: 'save-group'

%ol.joyride-list{data: {joyride: '', 'joyride-init' => {modal: true}}}
  %li{ data: {id: 'group-title', text: t('.next')} }
    %h4= t('.group')
    %p= t('.group_joyride_text')
  %li{ data: {id: 'group-url', text: t('.next')} }
    %h4= t('.group_url_joyride_title')
    %p= t('.group_url_joyride_text')
  %li{ data: {id: 'rules-title', button: t('.next'), options: 'tip_location:top;'} }
    %h4= t('.rules')
    %p= t('.rules_joyride_text')
  %li{ data: {id: 'stabilize', button: t('.next'), options: 'tip_location:top;'} }
    %h4= t('.stabilize_button')
    %p= t('.stabilize_button_joyride_text')
  %li{ data: {id: 'slider_0', button: t('.next'), options: 'tip_location:top;'} }
    %h4= t('.probability')
    %p= t('.probability_joyride_text')
  %li{ data: {id: 'locker_0', button: t('.next')} }
    %h4= t('.lock_button')
    %p= t('.lock_button_joyride_html')
  %li{ data: {id: 'add-rule', button: t('.next')} }
    %h4= t('.add_rule')
    %p= t('.add_rule_joyride_text')
  %li{ data: {id: 'save-group', button: t('.end')} }
    %h4= t('.save')
    %p= t('.save_joyride_text')

- footer_javascript do
  :javascript
    $(function(){
      Ruler.init({probability: '#{t(".probability")}'});
    });
- if current_user.groups.count.zero?
  - footer_javascript do
    :javascript
      $(function(){
        Ruler.joyride_toggle(true);
      });

app/views/groups/edit.html.haml
= render 'form'

app/views/groups/index.html.haml
%h2= t(:groups_list)

#groups
  - @groups.each do |group|
    .row.group
      .medium-6.large-6.columns
        .row.collapse
          %label
            = link_to group.name, group.full_url, target: :_blank
          .small-10.medium-11.large-11.columns
            %input.full-url-input.left{ type: :text, value: group.full_url, disabled: :disabled }
          .small-2.medium-1.large-1.columns
            %a.copy-to-clipboard.postfix{ role: 'copy-button', title: t('.copy_to_clipboard'), data: { clipboard_text: group.full_url, group_id: group.id }}
              %i.fi-download
      / .small-6.medium-2.large-2.columns
      /   %label
      /     = t(:hit_count_is, hit_count: group.rules.lazy.map(&:hit_count).map(&:to_i).sum)
      .small-6.medium-3.large-3.columns.right
        = link_to group, method: :delete, data: { confirm: t(:confirmation) }, class: [:button, :alert, :small] do
          %i.fi-page-delete
          = t(:destroy)
      .small-6.medium-3.large-3.columns.right
        = link_to edit_group_path(group), class: [:button, :small] do
          %i.fi-page-edit
          = t(:edit)
  .row
    .columns
      = link_to new_group_path, class: [:button, :small, :create_group] do
        %i.fi-plus
        = t(:create_group)
- footer_javascript do
  :coffee
    Ruler.zero_clipboard_init('#{t('.copied_to_clipboard')}')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t(:title)
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0" }
    %meta{name: "apple-mobile-web-app-capable", content: "yes"}
    %meta{name: "apple-mobile-web-app-status-bar-style", content: "black-translucent"}
    %link{ rel: "shortcut icon", href: "/favicon.ico", type: "image/x-icon" }
    %link{ rel: "icon", href: "/favicon.ico", type: "image/x-icon" }
    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags
    = yield :header_scripts
  %body
    .off-canvas-wrap
      .inner-wrap
        %nav#top-nav.top-bar.tab-bar{"data-topbar" => ""}
          - if current_user
            %section.left-small.show-for-small-only
              %a.left-off-canvas-toggle.menu-icon
                %span

          %section.middle.tab-bar-section
            %h1.title
              = link_to t(:redirectme), root_path
              %span.show-for-medium-up= [' - ', t(:redirectme_desc)].join
              %span.probability-sum{role: :stabilize}
          %section.right.top-bar-section
            %ul#sign_nav.right
              - if current_user
                %li.has-dropdown.show-for-medium-up
                  %a{href: "#"}= t(:menu_groups)
                  %ul.dropdown
                    = render 'shared/menu_groups_items'
                %li.has-dropdown.show-for-medium-up
                  %a{href: "#"}= t(:profile)
                  %ul.dropdown
                    = render 'shared/menu_profile_items'
              -# - else
              -#   %li
              -#     %a{ id: 'sign_in', href: '#sign_in', data: { 'reveal-id' => 'sign_in_modal', 'reveal' => ''} }= t(:sign_in)
        - if current_user
          %aside#side-menu.left-off-canvas-menu
            %ul.off-canvas-list
              = render 'shared/menu_profile_items'
              %li
                %label= t(:menu_groups)
              = render 'shared/menu_groups_items'
        #content_wrapper
          #content
            #in_content
              = yield
              %footer.row
                .small-6.medium-6.large-6.columns
                  .copyright.left
                    = t(:copyright)
                .small-6.medium-6.large-6.columns
                  = link_to t(:feedback_link), feedback_path, class: :right
        %a.exit-off-canvas

    #alert_box
    - unless current_user
      #sign_in_modal.reveal-modal{"data-reveal" => ""}
        #sign_in_form
          = form_for User.new, url: user_session_path, html: {class: 'row'} do |f|
            .large-4.columns
              = f.email_field :email, autofocus: !is_mobile_device?, placeholder: t('email')
            .large-4.columns
              = f.password_field :password, placeholder: t('password')
            .large-4.columns
              = f.submit t('sign_in'), class: [:button, :small]

    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :footer_scripts
    = render 'shared/flash_messages'
    :coffee
      $('#sign_in').on 'click', -> window.location.hash = '#sign_in'
      $(-> $(window).on('resize', -> Ruler.window_resize()).trigger('resize'))
      Ruler.fix_navigation()
      $(document).hammer(   ).on 'touch', '.reveal-modal-bg', -> $('[data-reveal]').foundation('reveal', 'close')
    - if production?
      = render 'shared/counters'

app/views/rules/_fields.html.haml
.field
  = f.label :master
  = f.check_box :master
.field
  = f.label :url
  = f.text_field :url
.field
  = f.label :expression
  = f.text_field :expression

app/views/rules/_form.html.haml
= form_for rule do |f|
  = render 'fields', f: f
  .actions
    = f.submit 'Save'

app/views/rules/edit.html.haml
%h1 Editing rule

= render 'form'

= link_to 'Show', @rule
\|
= link_to 'Back', rules_path

app/views/rules/index.html.haml
%h1 Listing rules

%table
  %tr
    %th Master
    %th User
    %th Url
    %th Expression
    %th
    %th
    %th

  - @rules.each do |rule|
    %tr
      %td= rule.master
      %td= rule.user_id
      %td= rule.url
      %td= rule.expression
      %td= link_to 'Show', rule
      %td= link_to 'Edit', edit_rule_path(rule)
      %td= link_to 'Destroy', rule, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Rule', new_rule_path

app/views/rules/new.html.haml
%h1 New rule

= render 'form'

= link_to 'Back', rules_path

app/views/rules/show.html.haml
%p#notice= notice

%p
  %b Master:
  = @rule.master
%p
  %b User:
  = @rule.user_id
%p
  %b Url:
  = @rule.url
%p
  %b Expression:
  = @rule.expression

= link_to 'Edit', edit_rule_path(@rule)
\|
= link_to 'Back', rules_path

app/views/shared/_counters.html.erb
<!-- Yandex.Metrika counter --><script type="text/javascript">(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter24150559 = new Ya.Metrika({id:24150559, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/24150559" style="position:absolute; left:-9999px;" alt="" /></div></noscript><!-- /Yandex.Metrika counter -->

app/views/shared/_errors.html.haml
- if resource.errors.present?
  - resource.errors.messages.each do |name, messages|
    - messages.each do |message|
      - footer_javascript do
        :javascript
          $(function(){$.fading_alert('#{message}', 'alert');});

app/views/shared/_flash_messages.html.haml
- flash.each do |key, value|
  :javascript
    $(function(){$.fading_alert('#{value}', '#{flash_class(key);}')});

app/views/shared/_menu_groups_items.html.haml
%li
  = link_to t(:groups_list), groups_path
%li
  = link_to t(:create_group), new_group_path

app/views/shared/_menu_profile_items.html.haml
%li
  %label= current_user.email
/ %li
/   = link_to t(:change_password), destroy_user_session_path, method: :delete
%li
  = link_to t(:feedback_link), feedback_path
%li
  = link_to t(:sign_out), destroy_user_session_path, method: :delete